### ISSUE TITLE
[Arithmetic\add & sub] should incompatible types parameters return a Runtime error?

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#1073]
**Describe the bug**
Try to add or subtract a color and another incompatible type returns null. I think that a runtime error should be a better behavior.
 
![image](https://user-images.githubusercontent.com/78623871/224854573-44b70fbd-b2cf-4bbd-8f2b-59ae622c63a1.png)

**Desktop (please complete the following information):**
 - OS: amd64/windows
 - Version v/0.9.83 b/170

**Additional context**
Discovered on #1072

**Comment by drkameleon** [comment]
You totally have a point here. 😉 

It's just that it's a tiny bit more complicated than it looks like to implement, plus we have to make sure there is no performance problems afterwards. 

Regarding normal arithmetic operations, what *is* happening is we do check about the main types... e.g. if a non-accepted type is passed. What we don't do is check whether the combination of two otherwise accepted types is not acceptable.

So, noted! I've been wanting to overwrite the whole Value-based operations code, so that's some very good timing! 🚀

**Comment by RickBarretto** [comment]
> plus we have to make sure there is no performance problems afterwards

Do Runtime errors have a big impact on performance?

**Comment by drkameleon** [comment]
> > plus we have to make sure there is no performance problems afterwards
> 
> Do Runtime errors have a big impact on performance?

Pfff... I have no idea how I managed to miss messages. Sorry! I just saw it!! 😞 

To reply, even if a week later:

Per se, runtime errors are not a problem. The problem is what type of tests we have to perform in order to catch them. And the more we go through the try-catch way (= Exceptions), the more likely it is that they *will* have some impact... (Good thing is Nim handles the whole thing quite graciously in terms of generated C code, but still...)

All in all, if I could automagically disable *all* error reporting functionality, I think the average performance gain would be around 15% (which is not negligible by any means, which is why it is to be reserved only for "portable"/production mode 😉 )
