### ISSUE TITLE
[Converters\to] getting an undefined behavior when creating `:complex` or `:rational` with some negative field 

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#1075]
Undefined behavior when creating a `:complex` or a `:rational` with a negative field

![image](https://user-images.githubusercontent.com/78623871/224856319-bd52541b-9d49-4765-a1db-c0833d73ca9a.png)
![image](https://user-images.githubusercontent.com/78623871/224856659-939b8874-a462-4f86-bc2a-2b833069ddb0.png)

**Desktop (please complete the following information)**
- OS: amd64/windows
- Version v/0.9.83 b/170

**Additional context**
Discovered on #1072

**Comment by drkameleon** [comment]
Since the passed block to `to` is just a block..., basically, we would normally have to evaluate the block beforehand.

Let me explain:

Let's take `to :complex [0 2.0]` for example; what do we want to convert to a complex number? the passed block... which is a constant block, with `0` and `2.0` instead.

Now, let's say you do `to :complex [0 neg 2.0]`; what does the VM understand? that you want to convert `0`, `neg` and `2.0` to a Complex number. Basically, `neg` is... just a word, that means nothing. So, in order for this to work - in this and every other similar case - we'd have to make the VM not only read but also execute the block, and give this `neg` its special meaning.

In a few words: `to :complex @[0 neg 2.0]`. 😉 

---

P.S. All that having been said, I'm still not sure there is no bug related to Complex or Rational numbers; so, all testing & feedback is more than ultra-useful! 😄

**Comment by RickBarretto** [comment]
I totally see your point here! Thanks for explanation

So, I think add this to documentation would be useful. I had sure that is wasn't related to `Arithmetic\(add|sub)` or `Converters\to`, but it was quite strange to me 😝.

And also, I see that `as.code` should return `to :complex @[i neg j]` instead of `to :complex [i -j], I don't know what is your opinion about it. 🙂

**Comment by RickBarretto** [comment]
- Properly fixed on #1117

**Comment by drkameleon** [comment]
Ooops!! I hadn't spotted it!! Re-opening (and doing things the right way... 😉 )
