### ISSUE TITLE
[Arithmetic\div] not working well for `:rational types`

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#1088]
**Describe the bug**
It's returning a wrong result.

For `:rational` & `:integer`
![image](https://user-images.githubusercontent.com/78623871/225788111-1e562021-83ea-4a84-97a7-9cb629495cf1.png)

For `:rational` & `:rational`
![image](https://user-images.githubusercontent.com/78623871/225788637-525fdb72-cdbf-4b10-8455-db0aa8a17efa.png)

**Desktop (please complete the following information):**
 - OS: win10/amd64
 - Version `v/0.9.83 b/170`

**Additional context**
Found on #1072

**Comment by drkameleon** [comment]
Great catch! Noted! 😉 

More and more work accumulating for the Value operations rewrite... lol

**Comment by drkameleon** [comment]
Question: why is it replicating the input?

I mean... I see:

```red
$> b/a
b/a
...
```

This definitely isn't supposed to be happening. 🤔

**Comment by drkameleon** [comment]
OK, and another comment...

Basically, re-looking at it, I don't think this is to be considered a bug... or perhaps it should, you tell me:

`/` in Arturo (or `div`) is meant to be used for *integer* division, so that's what the result of the operation is...

For floating division, we'd normally use `//` (or `fdiv`) and then - I think - we would have the results you expected:

<img width="327" alt="Screenshot 2023-03-17 at 12 57 02" src="https://user-images.githubusercontent.com/1265028/225898053-a4cd1524-9f32-4472-b6d0-b0d2b09fc907.png">

Now, the only case where the `/` means a floating division, implicitly, is when one of the two parameters is already a `:floating` number. The question would be: what should we do with `:rational` values? Should divisions including at least one Rational number implicitly be floating-style division, or do we leave it as-is? (with `/` meaning what it means, and `//` being the floating division)

**Comment by RickBarretto** [comment]
> Question: why is it replicating the input?

I really don't know. I forgot to mention it. Also, Let me try it on Git Bash's prompt and VsCode prompt to see if it have the same behavior or if it is just for Msys2. Also, I'm having other problems with Arturo's REPL on Msys2 and I can open issues about it.

**Comment by RickBarretto** [comment]
> The question would be: what should we do with :rational values?

Good question...

**Comment by drkameleon** [comment]
> > Question: why is it replicating the input?
> 
> I really don't know. I forgot to mention it. Also, Let me try it on Git Bash's prompt and VsCode prompt to see if it have the same behavior or if it is just for Msys2. Also, I'm having other problems with Arturo's REPL on Msys2 and I can open issues about it.

I hope I haven't left any stray `print` anywhere... although I confirmed it right now. Are you using the latest/master branch version?

**Comment by RickBarretto** [comment]
> I hope I haven't left any stray print anywhere... although I confirmed it right now. Are you using the latest/master branch version?

I'm current using `v/0.9.83 b/170`, It's working well on VsCode's terminal. It's just a problem for Msys2's terminal.

**Comment by RickBarretto** [comment]
> Very weird! I'll have a look into it! 😉

Sure, thanks!
