### ISSUE TITLE
[Arithmetic\pow] wrong error message

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#1132]
**Describe the bug**

So `pow :quantity :integer` when using currency is returning a wrong error message:

```red
$> pow 2:usd 2
; >> Runtime | incompatible operation between quantities
;      error | attempted: mul
;            | with:  (currency)  (currency)
```

It should be:
```red
$> pow 2:usd 2
; >> Runtime | incompatible operation between quantities
;      error | attempted: mul
;            | with:  (currency)  (integer)
```

We can't even have an (currency) as second parameter 😅, look:

```red
$ info 'pow
; |--------------------------------------------------------------------------------
; |            pow  :function                                           Arithmetic
; |          alias  ^
; |--------------------------------------------------------------------------------
; |                 calculate the power of given
; |                 values and return result
; |--------------------------------------------------------------------------------
; |          usage  pow valueA :integer :floating :complex :rational :literal :quantity
; |                     valueB :integer :floating
; |
; |        returns  :integer :floating :complex :rational :quantity :nothing
; |--------------------------------------------------------------------------------
```

**Desktop (please complete the following information):**
- version : `v/0.9.83 b/331 @ 2023-03-30T15:09:55-03:00`
- arch    : `amd64/windows`

**Additional context**
- Found while doing #1130

**Comment by drkameleon** [comment]
Totally! That's absolutely correct.

As for Quantity values as a right-hand parameter in the power operation... well, that would be really funny to see what the result would be... I mean 2 in the power of "3 meters" - that's cryptic to say the least lol

Now, kidding aside, the power operation is one of the most difficult ones, even if we take Quantity out of the equation. As you can see, it has the most limited support for values (for the right-hand part) compared to all other arithmetic operations... but for very good reasons. 

P.S. The only one that I *think* we could "easily" add to the list would be Rationals (since they are directly convertible to `:floating`... Hmm... 🤔 )

**Comment by drkameleon** [comment]
Just spotted the *why* of the above error (not that it justifies the error itself, but well...):

https://github.com/arturo-lang/arturo/blob/master/src/vm/values/operators.nim#L1139-L1146

Actually, the power function is defined internally as multiplication, which is precisely what it is... That's why the function triggering the message above (look closely ^ 😉 ) is actually `mul` and not `pow`. And, technically, *yes* `mul` is multiplying quantities together... Now, is it such a self-explanatory error? Not really sure..

Right now, the exact same thing (in the PR) works like this:

```
$> 2:usd ^ 2
>> Runtime | incompatible operation between quantities
     error | attempted: mul
           | with: 2USD (currency) 2USD (currency)
```

In theory, quite precise if you think about it. In practice, still quite confusing... Hmm... 🤔

**Comment by drkameleon** [comment]
As another sidenote... so that you understand the complexity of the whole thing:

if you do e.g. `3:m ^ 3`, you may think it's like (3^3):(m^3), but what it actually does (and that is to be able to use the overflow mechanisms and unit-conversion formulas from the multiplication, which are already there) is:

- 3:m
- 3:m * 3m -> 9:m2
- 9:m2 * 3:m -> 27:m3

**Comment by drkameleon** [comment]
Follow-up: (I think I found a workaround; it's not the best ever, and I wouldn't do it - all this `try`/`catch`ing - if it was a performance critical location, but for that precise scenario, I think... no harm done!)

https://github.com/arturo-lang/arturo/pull/1135#issuecomment-1492962809
