### ISSUE TITLE
Parser issues giving me a SIGSEGV error because of code formatation

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#1183]
**Describe the bug**
When I was creating the PR #1182 [I discovered an issue with the parser][fixing-sigsegv-commit].
Well, it's returning a SIGSEGV error because of code formatation.

**To Reproduce**

This code returns SIGSEGV locally or timeout in Playground
```red
testFunction: $[
	data :dictionary
	asset :integer
][
	print [ color #red "- Downloading new version..." ]
]

testFunction #[some: "data"] 0
; timeout: sending signal KILL to command '/var/www/arturo-lang.io/arturo-0.9.83-safe-linux'
```

But this code works properly:
```red
testFunction: $[data :dictionary asset :integer][
	print [ color #red "- Downloading new version..." ]
]

testFunction #[some: "data"] 0
; - Downloading new version...
```

They are the exact function, with the exact parameters... Arturo should be agnostic to formatation and for some reason it's not being this at the moment.

**Expected behavior**
```red
testFunction : $[
	data :dictionary
	asset :integer
][
	print [ color #red "- Downloading new version..." ]
]

testFunction #[some: "data"] 0
; - Downloading new version...
```

**Desktop:**
 - arch: `amd64/windows`
 - version: `v/0.9.83 b/407 @full 2023-05-08T17:16:24-03:00`

**Playground:**
 - arch: `x86_64/linux`
 - version: `v/0.9.83 @safe 2023-02-10T16:02:25+00:00`

**Additional context**
- [Timeout/SigSegv code][sigsegv-code]
- [The same code but working fine][working-code]

[fixing-sigsegv-commit]: https://github.com/arturo-lang/arturo/pull/1182/commits/f37684018028d3400671406a6fdf6cf7fb7fbb50
[sigsegv-code]: http://arturo-lang.io/playground?sQQwty
[working-code]: http://arturo-lang.io/playground?DMbnAp

**Comment by drkameleon** [comment]
That's a *very* interesting. Well spotted!!! 🚀 

I'm pretty sure it has to do with the AST generation:

basically, at the AST level, we have to keep track of all the functions (for their arity). But what can we do if a function has been declared in the exact same block where it's used?

I mean... think of it this way... we process the block above... we know what `print` does beforehand and that it takes 1 argument, so the final AST tree will tree it like this and search for 1 argument. But what about `testFunction`? Is it a variable or a function? Basically, it's nothing until it's declared. But the declaration (as a function) takes place in the exact same block.

So, the only way to try and register it as a function with some given arity (before it actually becomes a function) is by trying to guess-timate its argument at the AST stage.

And there, I guess, I didn't handle newlines properly (totally to be expected: the newline handlling - there solely because of error reporting - is the most tricky part of it all!)

Let's see... 😉

**Comment by RickBarretto** [comment]
Got it! Thanks for the explanation.

Well, probably I had found this error about a month ago, but I couldn't find what were happening at that moment...

I found at this time because I was dealing with a relative smaller code, so I commented a lot of parts to discover what was breaking, and here we are! 🙂 

**Reference**
- https://github.com/RickBarretto/poliglota/issues/15

**Comment by drkameleon** [comment]
Awesome really. You managed to isolate the issue *so* well, that I guarantee you this will be fixed fast! :)
