### ISSUE TITLE
call.external doesn't work

### ISSUE THREAD

**Issue by scifx** [arturo-lang/arturo#1194]
I am running under the linux mint system, and the  [call.external](https://arturo-lang.io/documentation/library/core/call/) function example reports an error. And there is also an omission in the example of the official document, the end of the #include statement is empty.
`>> Runtime | File: test.art
     error | Line: 1
           | 
           | dynamic library could not be loaded:
           | libmylib.so
`

**Comment by drkameleon** [comment]
Thanks a lot for the issue report! 🚀 

What is the error you're seeing after calling `call.export`?

Regarding the example you mention, you are totally right: basically the example has been messed up when converting to HTML. Writing it down so that it gets fixed! 😉 

This is the correct example for `call`:

```
            ; Calling external (C code) functions
            
            ; compile with:
            ; clang -c -w mylib.c
            ; clang -shared -o libmylib.dylib mylib.o
            
            ; #include <stdio.h>
            ;
            ; void sayHello(char* name){
            ;    printf("Hello %s!\n", name);
            ; }
            ;
            ; int doubleNum(int num){
            ;    return num * 2;
            ;}

            ; call an external function directly
            call.external: "mylib" 'sayHello ["John"]

            ; map an external function to a native one
            doubleNum: function [num][
                ensure -> integer? num
                call .external: "mylib"
                    .expect:   :integer
                    'doubleNum @[num]
            ]

            loop 1..3 'x [
                print ["The double of" x "is" doubleNum x]
            ]
  ```

**Comment by scifx** [comment]
Thank you for your hard work and prompt reply! I amended the #include statement earlier and got the error message mentioned above. And just now I copied your code and tried again and got the same error. My source files are mylib.c and test.art. Mylib.c is compiled to get mylib.o and libmylib.dylib. `dynamic library could not be loaded: | libmylib.so`What could be the reason? If it is convenient, can you also compile and run it?

(Off-topic, I have been following your project for a long time, it’s really a great language! I’ve been using it all the time, and it’s very convenient to solve daily problems. Thank you very much for your efforts. Inevitably, I encountered many problems and bugs during the period, At that time, I will take the time to give feedback.

**Comment by drkameleon** [comment]
First of all, thanks A LOT for you kind words. You cannot imagine how good it makes me feel, especially after the work that has gone into the project. And... don't worry about issues; the more we spot the better. It's only by solving them that we can make the language even better... 😉 

> I amended the #include statement earlier and got the error message mentioned above. And just now I copied your code and tried again and got the same error. My source files are mylib.c and test.art. Mylib.c is compiled to get mylib.o and libmylib.dylib. dynamic library could not be loaded: | libmylib.soWhat could be the reason? If it is convenient, can you also compile and run it?

I *guess* - though I'm not 100% sure - it has to do with Linux and the way it tries to locate the library. Apparently, it's looking for a `.so` file, but I'm not sure how you should properly address it... 🤔 

Could you play a bit with this part: `call .external: "mylib"`?

I mean... try perhaps `libmylib`? (I may be talking total nonsense here, simply because I haven't recently done that on Linux, but I will try to experiment a bit on by tomorrow morning! :) )

**Comment by scifx** [comment]
Seriously, as a designer, I can see that Arturo is really a work of art, not only the language itself but also help documents, typography and tips, all in a simple and pragmatic style, I can fully imagine your mood, just as I encountered it.

Regarding the bug, changing the name doesn’t work either. I tried recompiling another `libmylib.so`, or wrote a dynamic library for testing with nim. Under the premise that python can be called correctly, the same error is still reported with arturo, which means that it is very likely to be a problem in the call function. Maybe you really need to actually test it, thanks!

**Comment by drkameleon** [comment]
> Seriously, as a designer, I can see that Arturo is really a work of art, not only the language itself but also help documents, typography and tips, all in a simple and pragmatic style, I can fully imagine your mood, just as I encountered it.

❤️ 

> Regarding the bug, changing the name doesn’t work either. I tried recompiling another libmylib.so, or wrote a dynamic library for testing with nim. Under the premise that python can be called correctly, the same error is still reported with arturo, which means that it is very likely to be a problem in the call function. Maybe you really need to actually test it, thanks!

I just tested the whole thing on Ubuntu and I think I managed to solve it (although obviously we should make it so that no such "hacks" are needed).

So... to be precise, I'll describe the whole procedure.

Preparation
======

**mylib.c**

```c
#include <stdio.h>

void sayHello(char* name){
    printf("Hello %s!\n", name);
}

int doubleNum(int num){
    return num * 2;
}
```

Compile with: 

```bash
clang -c -w mylib.c
```

Link with:

```bash
clang -shared -o libmylib.so mylib.o
```

Now, we should have ended up with `libmylib.so` file.

**mylibtest.art**

```red
call.external: "./libmylib.so" 'sayHello ["John"]

; map an external function to a native one
doubleNum: function [num][
    ensure -> integer? num
    call .external: "./libmylib.so"
         .expect:   :integer
         'doubleNum @[num]
]

loop 1..3 'x [
    print ["The double of" x "is" doubleNum x]
]
```

⚠️ Watch how we set the path 😉 ; this the key

Running:

```bash
arturo mylibtest.art
```

The result
====
<img width="286" alt="Screenshot 2023-05-30 at 16 04 14" src="https://github.com/arturo-lang/arturo/assets/1265028/4be1bda3-5d09-41c1-820e-be1b81a4b6d0">


------

Please, tell me if it worked for you! In the meantime, I'll create an issue for this so that path handling is fixed in the case of Linux/*nix/etc. 🚀

**Comment by scifx** [comment]
It works! It is executed correctly. To be sure, I also tested the dll written in the nim language, and it can also be executed. Thanks for your careful guidance. In fact, according to the daily usage habits of linux, it is "./libmylib.so". Even if I wrote the path correctly in python, I was still misled by the arturo help documentation. Thanks again!

**Comment by RickBarretto** [comment]
I'm on Windows 10 using Msys2/Mingw64, and my `gcc` generates a `libmylib.so` too instead of `libmylib.dylib`...

> Therefore, in order to fix this problem, is it necessary to change the path parameter of the call function to the relative path of each operating system file, in line with the daily calling habits?

That's a good question...

> if you tell the user that this is the relative path of the dynamic library file, it will be very intuitive

:wink: Thanks for the advise! It's a good idea IMO.
