### ISSUE TITLE
If statement should skip the second condition if the first is false

### ISSUE THREAD

**Issue by jinyus** [arturo-lang/arturo#1275]
**Describe the bug**
When doing an `and` comparison, it evaluates the second condition even when the first is false.

Playground: [http://arturo-lang.io/playground?m7mq36](http://arturo-lang.io/playground?m7mq36)
```
nums: [1,2,3]

; ERROR: array index out of bounds: 3
; the first condition isn't true so 
; the second should not be evaluated

if size nums > 3 and? nums\3 == 4 [
    print "nums has 4th element"    
]
```

Here, I'm check that the size of the array is gt 3 so I know it's safe to access the 3rd index.

**Comment by drkameleon** [comment]
Hi and thanks a lot for the issues! 😄 

Now, regarding this...

First of all, regarding the `and?` command, since it works like pretty much every other Arturo function, it's a function; so it normally goes *before* its arguments.

So, we'd have: 
```
if and? size nums > 3 nums\3 == 4 {]
```

Now, to the gist of the question:

To make it behave as you suggest, all you'd have to do is enclose each one of its arguments in a block.

So, your code would be:

```red
nums: [1,2,3]

if and? [size nums > 3][nums\3 == 4][
    print "nums has 4th element"    
]
```

The exact same thing works for all logical functions: `or?`, `xor?`, etc 😉

**Comment by jinyus** [comment]
Oh, I see...thanks
