### ISSUE TITLE
[Iterators] Weird issue with iterators

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#1564]
Basically, I have 2 files in my repo.

```
unitt.art
tester.art
```

`unitt-tester` uses `unitt` via importing.

I have the following for each of them:

```red
; tester.art
import {unitt}

do ::

    print "===> Finding *.art"
    runTests.suppress.glob: "*.art" "tests"
    
    print "===> Finding *.test.art"
    runTests.suppress.glob: "*.test.art" "tests"
```

```red
; unitt.art

runTests: $[testPath :string][

    ; Important to final statistics
    passed: 0
    failed: 0

    ; Important to return error code.
    ; If some test throw an error and don't explicitly catches it,
    ; this should not return 0 as error code, but 1, instead.
    fatalError: false

    pattern: (attr 'glob)?? "test*.art"
    testPrefix: first split.by: "*" pattern
    testSuffix: last  split.by: "*" pattern

    isTestFile?: $[file :string][
        ;; description: « Checks if `file` starts with 'test' and is an .art file

        filename: last split.path file

        return and? 
            prefix? filename testPrefix
            suffix? filename testSuffix
    ]

    ; ===> This select is broken <====
    testfiles: select (list.recursive testPath) 'file -> isTestFile? file

    ; The tests execution
    loop testfiles 'file [ 
        print ~"\n===== |file| =====\n"

        result: execute.code ~"|sys\binary| |file|"
        output: split.lines result\output

        loop output 'line [
            print line
            if in? '✅' line -> inc 'passed
            if in? '❌' line -> inc 'failed
        ]

        ; if some test throws an error
        if result\code > 0 -> 
            fatalError: true

    ]

    print ~"\n===== Statistics =====\n"
    print ~"⏏️  TOTAL:  |passed + failed| assertions"
    print ~"✅ PASSED: |passed| assertions"
    print ~"❌ FAILED: |failed| assertions"
    print ~"\n===== ========== =====\n"

    exit?: not? attr 'suppress
    failed?: or? (fatalError) (failed > 0)
    if and? exit? failed? 
        -> exit.with: 1

]

...
```

Basically, when I call `arturo tester.art`, I get:

```
===> Finding *.art

===== tests\append-test.art =====
...
===== tests\append.art =====
...
===== tests\append.test.art =====
...
===== tests\drop-test.art =====
...
===== tests\drop.test.art =====
...
===== tests\dup.art =====
...
===== tests\test-append.art =====
...
===== tests\test-append.test.art =====
...
===== Statistics =====

⏏️  TOTAL:  40 assertions
✅ PASSED: 32 assertions
❌ FAILED: 8 assertions

===== ========== =====

===> Finding *.test.art
>> Runtime | File: unitt-tester.art
     error | Line: 47
           |
           | cannot perform select
           | incorrect attribute type for .with -> :integer
           | accepts :literal
```

But, that is the stranger part, if I comment-out the first or second runner in `tester.art`, this works fine.
This just breaks when one is called after the another one.

## Additional info

- version : v/0.9.83 b/2276 @ 2024-01-25T21:43:47-03:00
- arch    : amd64/windows

**Related:**
- Found when trying to solve: https://github.com/RickBarretto/unitt/issues/3

**Comment by RickBarretto** [comment]
I tried to replace `select` by a simple `loop`, the problem persists.

```red
testfiles: [] 
    loop (list.recursive testPath) 'file -> 
        if (isTestFile? file) -> append 'testfiles file
```

**Comment by drkameleon** [comment]
Can you try replacing the `return` inside `isTestFile?` with... nothing at all (it's the last value so it will actually *return* it) and let me know how it went?

(It may sound like a very weird suggestion but I've had a hunch for some time that there may be an issue with `return` and its AST transformations...)

**Comment by drkameleon** [comment]
Also, another hint: https://github.com/arturo-lang/arturo/pull/1507

Although I haven't advertised it too much (and the [first version](https://github.com/arturo-lang/arturo/pull/1312) was a bit messy - implementation-wise), I think a) it's absolutely solid, b) it doesn't look too bad.

**So... what I'm talking about:**

A well-known issue that comes with the very design of Arturo is the one thing that defines it: arity.

Arity (of functions) is what makes the AST processor group things correctly and without it being known *in advance*, it obviously wouldn't work. 

Let's say... the AST processor sees `print`:

- it looks up our current symbol table. 
- Is it a function? 
- Great! How many parameters does it take?
- 1! Awesome, now let's try to group it with this one parameter

In the case of using `import` statements, the problem is that if we process a block of commands when e.g. the first statement is an import statement, the first command (the `import`) is going to be processed just fine but any command *coming from* that import will not - simply because it's not known at the time the block is processed (the block is processed and THEN it's executed - thus importing whatever there is to be imported...)

That's why we'd need to use functions coming from that `import`ed module in a different block.

The exact same thing would be needed if we e.g. create an object that has methods. Calling its methods will work but *not* in the same block as its creation.

So, technically, up to now, the idea would be:

```
import 'somemodule

do [
    ; ... use functions from that module
]
```

or with OOP:

```
obj: to :sometype []

do [
    ; ... use some method from obj
    ; e.g. obj\someMethod 123
]
```

Here's where the `!` trick comes into play.

With this new "syntactic sugar" the above can be written like:

```
import 'somemodule!

; ... use functions from that module
```

or:

```
obj: to :sometype []!

  ; ... use some method from obj
  ; e.g. obj\someMethod 123
```

Technically, you could say that `!` wraps the whole thing AFTER it in a `do [ ... ]`. (But there's a tiny secret: it does that - more or less - but it's a one-byte command for our VM, so it has to be even faster 😉 )

To highlight it a bit more...

This:

```red
a: 1
do [
    b: 2
    do [
         c: 3
    ]
]
```

Would become:


```red
a: 1!
b: 2!
c: 3
```

(again, not quite: it's faster than `do`s and more... magic! But you get the idea... 😉 )

**Comment by RickBarretto** [comment]
I discussed this in off, with @drkameleon.

So, I'll use this to explain what is happening for future questions.
The error is in:

```red
    exit?: not? attr 'suppress
    failed?: or? (fatalError) (failed > 0)
    if and? exit? failed? 
        -> exit.with: 1
```

Basically, `exit` takes no attributes, since it does not takes any positional argument.
Before the AST implementation, exit actually had an `.with :integer` attribute, but things have been changed since there and to don't mess up things with attributes, the attributes should be put before the last parameter of a function. 
Remembering that Arturo works with fixed arity, so this totally makes sense in our context.

To solve this, replace `exit.with` by `panic.with`, or just `panic`.
