### ISSUE TITLE
v0.9.83/82 cannot be built from source without patching

### ISSUE THREAD

**Issue by Yewzir** [arturo-lang/arturo#1661]
There's a colon at the end of lines 952 and 1036. Therefore, the build process abruptly terminates due to invalid indentation errors.

https://github.com/arturo-lang/arturo/blob/daa327c4d524d977bf549a24be0933fed496aa6b/src/library/Numbers.nim#L952

https://github.com/arturo-lang/arturo/blob/daa327c4d524d977bf549a24be0933fed496aa6b/src/library/Numbers.nim#L1036

They're present in v0.9.82 as well.

https://github.com/arturo-lang/arturo/blob/fa4b7c3c06ab22fb2d984db03a16ecba8640a4b1/src/library/Numbers.nim#L952

https://github.com/arturo-lang/arturo/blob/fa4b7c3c06ab22fb2d984db03a16ecba8640a4b1/src/library/Numbers.nim#L1036

**Comment by Yewzir** [comment]
I would've greatly appreciated if I'd just received some minimal feedback at the very least. Unfortunately, this stands in my way and therefore I'm closing the issue as not planned.

**Comment by drkameleon** [comment]
> I would've greatly appreciated if I'd just received some minimal feedback at the very least. Unfortunately, this stands in my way and therefore I'm closing the issue as not planned.

Apologies for the non-reply. For whatever reason, I only noticed your open issue right now! (and if I had, I obviously totally forgot about it). Sorry! :)

**Comment by drkameleon** [comment]
Re: the main question, I believe the cause lies in the Nim version that is used.

If I'm not mistaken, the Nim version at the time of the release was 1.6.14 (or somewhere there). Then Nim changed some things - as usual - and kind of made our previous source irrelevant (or at least irrelevant without a few tweaks here and there).

I would personally suggest:

- either compiling Arturo v0.9.83 with Nim =<  v1.6.16
- or simply using the master branch version (v0.9.84-alpha) with the latest Nim (= v2.0.8)
