### ISSUE TITLE
Arturo is not on http://RosettaCode.org/wiki/Rosetta_Code

### ISSUE THREAD

**Issue by PatrickDGarvey** [arturo-lang/arturo#184]
You may be missing a good publicity opportunity.
https://rosettacode.org/wiki/Help:Adding_a_new_programming_language

**Comment by drkameleon** [comment]
@PatrickDGarvey Hi!

Arturo [*is* on Rosetta Code](https://rosettacode.org/wiki/Arturo) - it's just that... I'm working too much on the language itself and I haven't had time to update/upload the examples. Some are obsolete (from Arturo's version years ago), some are not valid anymore and there are many new ones (on which I'm working on a daily basis) which are not there.

That's why... any help would be more than welcome! :) 

As a matter of fact, I've already [opened an issue myself to keep track of all the Rosetta Code samples](https://github.com/arturo-lang/arturo/issues/153) (ALL tested and tried)... so if you want to lend a hand, I'd be more than grateful!

**Comment by PatrickDGarvey** [comment]
Sorry, I didn't check my assertion before posting the issue. You're right
Arturo is there.

At the moment, I'm trying to get a basic knowledge of RosettaCode. When
Arturo showed up in my Quora digest, I thought to make the suggestion in an
issue report before checking my assertion. It's too early in the morning
for me to be making such reports. Got to wake up, first.

Sorry.

**Comment by drkameleon** [comment]
@PatrickDGarvey 
Haha! Never mind!

It's just a good reminder for me that I *have to* sit down and start migrating the updated snippets there. I know perfectly well that's it's a valuable source - especially for not-so-well-known languages.

So, thanks! :)

**Comment by drkameleon** [comment]
As of today, all existing Rosetta code examples have been uploaded/updated to Rosetta Code - and [all Arturo code snippets at Rosetta code](https://rosettacode.org/wiki/Category:Arturo) are up-to-date (with obsolete ones gone). 

So, I'm "officially" closing this issue. :)

**Comment by PatrickDGarvey** [comment]
Excellent.
