### ISSUE TITLE
Windows nightly pre-built binaries: libgmp-10.dll is missing

### ISSUE THREAD

**Issue by progamateur** [arturo-lang/arturo#284]
Os: Windows 10
Version: 20H2
System/processor type: 64 bits

Arturo installation:
Using pre-built binaries: 
-> https://github.com/arturo-lang/nightly/releases
-> Latest nightly @ 2021-04-28 (c3cacbc)
-> download : arturo-0.9.75-2021-04-28-Windows-mini.tar.gz
-> file unzipping (7-zip)

**Running arturo.exe (.\bin directory) gives the following message : libgmp-10.dll is missing**

Note:
I solved the problem by copying in the .\bin folder this dll which is available in the MinGW distribution hosted by the nim-lang site (https://nim-lang.org/download/mingw32.7z or https://nim-lang.org/download/mingw64.7z).

**Comment by drkameleon** [comment]
Thanks A LOT for letting me know.

I don't know what's going on, since the basic premise of having 2 separate builds - the "mini" and the "full" version - is to have a lighter build, without so many dependencies (namely Sqlite and GMP), obviously by not having a few not-so-common functionalities.

Once I figure out how to get rid of the extra dependencies, I'll start shipping both versions for Windows, initially by packaging together all the needed DLLs (and at some later stage, hopefully, by static-linking all that's necessary for Arturo to run properly).

Let's see...

In any case, thanks a lot! :)

Btw, in case you want to have a look... you may join the "official" server @ Discord: https://discord.gg/YdVK2CB , I mean in case there is something simple you want to ask about. There are already many people, me included, willing to help out. 😉

**Comment by drkameleon** [comment]
Right now, the issue seems to have been resolved - mainly thanks to your observation :)

If you check out the latest nightly, both binaries for Windows (yep, now we have both of them: the "mini" and the "full" one) should be working fine, without any issue whatsoever.

https://github.com/arturo-lang/nightly/releases/download/tag-2021-04-29/arturo-0.9.75-2021-04-29-Windows-mini.tar.gz
https://github.com/arturo-lang/nightly/releases/download/tag-2021-04-29/arturo-0.9.75-2021-04-29-Windows-full.tar.gz

Let me know how it went if you have time! :)

**Comment by progamateur** [comment]
I've tested the full Windows version.

There is a compatibility issue with the provided libgmp-10.dll version.

A priori you'v used the libgmp-10.dll version founded in ...\mingw64\libexec\gcc\x86_64-w64-mingw32\9.2.0 folder (nim minGw distribution)

For me the working version is the one founded in ...\mingw64\gdb64\bin or ...\mingw64\gdb32\bin folders (against the 64/32 bits os/processor)

**Comment by drkameleon** [comment]
Hmm... Thanks for letting me know. I'll have a look into it.

I have no idea what the difference between the 2 DLLs is to be perfectly honest...

Have you tested the *mini* build as well?

Also, since you are on Windows and using the REPL, I think you'd have a much better experience if you used `--no-color` when running Arturo from the command-line. (basically, it suppresses all color output, which - on Windows - ends up like gibberish... )

**Comment by drkameleon** [comment]
P.S. I replace the DLL in question with the one you mentioned, so - by tomorrow - the new nightlies will include this one.

Let's see... (I guess I'll have to set up a Windows laptop I have somewhere, only to be able to test it myself. There's no other way around...)

**Comment by progamateur** [comment]
mini build is ok (no more libgmp.dll and sqlite3_64.dll files).
For the mini build, did you use the nim compilation option -d:NOGMP?
Is it possible to make available the nightly sources? (for now only tags are available )

**Comment by drkameleon** [comment]
Glad to hear that - at least this one - works without glitches! :)

Regarding mini builds, you could easily check what they are about by having a look at the installation option at the install script: basically [it's more than `NOGMP`](https://github.com/arturo-lang/arturo/blob/master/install#L112).

Regarding "nightly sources", I'm not sure I understand what you mean. The current sources of each nightly are shipped together with all the different pre-built binaries, e.g. @ https://github.com/arturo-lang/nightly/releases/tag/tag-2021-04-29

<img width="822" alt="Screenshot 2021-04-29 at 13 11 19" src="https://user-images.githubusercontent.com/1265028/116542311-d25d2500-a8ec-11eb-8ead-6e90a7011699.png">

(I must be missing something in your question... Please, let me know! ;-) )

**Comment by progamateur** [comment]
. Click on "Source code (zip)" downloads  "nightly-tag-2021-04-29.zip" file
. unzipping nightly-tag-2021-04-29.zip gives the following folder hierarchy: 
       ...\nightly-tag-2021-04-29
                      |--> \.github
                      |               |--> \workflows
                      |                               |--> build.yml
                      |--> READMEmd
So, no source code files.

.Click on "Source code (tar.gz)" downloads  "nightly-tag-2021-04-29.tar.gz file
. unzipping nightly-tag-2021-04-29.tar.gz gives the following folder hierarchy: 
       ...\nightly-tag-2021-04-29.tar
                 |--> \nightly-tag-2021-04-29
                 |                   |--> \.github
                 |                   |               |--> \workflows
                 |                   |                               |--> build.yml
                 |                   |--> \nightly-tag-2021-04-29
                 |                   |                |--> \.github
                 |                   |                |              |--> \workflows
                 |                   |                |                              |--> \build.yml
                 |                   |                |--> README.md
                 |                   |--> pax_global_header            
                 |                   |--> README.md
                 |--> nightly-tag-2021-04-29.tar

So, no source code files.

**Comment by drkameleon** [comment]
Totally spot on! I had missed it 100%.

What happens is... the GitHub action packages the sources itself, automatically. Only what happens is... it packages the sources of the repository it's running from, in which case it's not the right one!

I've just opened an issue to track it down and I'll look into it: https://github.com/arturo-lang/nightly/issues/1

Thanks a lot for letting me know!

**Comment by drkameleon** [comment]
Related: #592
