### ISSUE TITLE
Couple of Improvements and Fixes

### ISSUE THREAD

**Issue by theAkito** [arturo-lang/arturo#3]
First of all, thank you for this project. It seems like a very great programming language.

I have a couple of minor issues that I'd like to document:

- [ ] Build Script does not error out properly, when something goes wrong.
- [ ] Build Script does not get all needed compile time dependencies (`libgmp-dev` is currently missing).
- [ ] Build Script uses non-standard installation directory (`/usr/local/bin`) which is, for example, not included in Debian's `PATH` by default.
- [ ] README does not mention, that you need the newest `devel` version of Nim to be able to successfully compile this project.

If you don't mind, I'd like to fix these issues myself. I also would be glad to solve some of the goals mentioned in the README, at some point.

**Comment by drkameleon** [comment]
Well, you are absolutely right about all of the points.

They are already in my to-do list, but I cannot seem to find the time to fix everything.

So, if you're willing, you're more than welcome!

Regarding `libgmp-dev` I was thinking of being a bit... flexible. I mean: I'm planning on having different 'versions', a super-mini one (light, with small size, zero dependencies) and probably different ones - opting for example for GMP, or not, since I'm thinking that most users would probably never need to play with super-big numbers, although they should have the option if the want to.

**Comment by drkameleon** [comment]
Another idea/goal, in the near future, is to be able to serve the final C code - without requiring from the user to install Nim at all. Or even better, do it the way Rebol did: just serve standalone/no-dependencies binaries. It should be possible. 

For now, judging by a couple of tests I've run, compiling on macOS Catalina and sending the binary to High Sierra, I failed miserably. Oh well...

**Comment by theAkito** [comment]
> Another idea/goal, in the near future, is to be able to serve the final C code - without requiring from the user to install Nim at all. Or even better, do it the way Rebol did: just serve standalone/no-dependencies binaries. It should be possible.

I personally strongly prefer the latter. I'm against supporting further persistence or dependency on C, when there are so much better languages, that should replace C.

That said, that can be decided on much later, I think. First, this language has to mature much more! 😄

**Comment by drkameleon** [comment]
> > Another idea/goal, in the near future, is to be able to serve the final C code - without requiring from the user to install Nim at all. Or even better, do it the way Rebol did: just serve standalone/no-dependencies binaries. It should be possible.
> 
> I personally strongly prefer the latter. I'm against supporting further persistence or dependency on C, when there are so much better languages, that should replace C.
> 
> That said, that can be decided on much later, I think. First, this language has to mature much more! 😄

I think it's feasible. Let's see... 👍

**Comment by drkameleon** [comment]
Given that the above PR pretty much addressed all the aforementioned issues (basically, by circumventing my own script and doing it all via Nimble), however - since the [previous build script](https://github.com/arturo-lang/arturo/blob/master/build.sh) will remain as-is -  if @theAkito you're still willing to work on it, let me know and I'll re-open the issue.
