### ISSUE TITLE
Windows .cmd installer for self-building

### ISSUE THREAD

**Issue by Kyllingene** [arturo-lang/arturo#385]
**Is your feature request related to a problem? Please describe.**
Attempting to build arturo on Windows is painful, because there is no `install` script for Windows and WSL has some problems with it.

**Describe the solution you'd like**
A Windows `install.cmd` or something equivalent would streamline the building process for Windows tremendously.

**Describe alternatives you've considered**
Somehow altering the existing `install` script to work with WSL would fix the issue as well, but I'm not sure if that's possible.

I attempted to build with Nim, but ran into issues (particularly with a missing `gmp.h`); making it easier to build with Nim directly could also help.

**Additional context**
I would use the `curl` method of installation, but something is wrong with it on my machine at the moment; either way, being able to build on Windows would be helpful.

**Comment by drkameleon** [comment]
Hi!

And thanks a lot for the suggestion!

I admit the support for Windows is not as complete as it should be - the main reason being that I'm totally not a Windows developer or even familiar with the OS (as a matter of fact, I don't think I even have a machine running Windows right now, but that could be solved somehow).

In any case, I'll definitely look into it, as it's important for everyone to be able to build/install Arturo on any system, in the easiest possible way. (Any ideas/pointers would be more than welcome!)

In the meantime, I could point you to the Windows CI build workflow (the one running automatically on a Windows server, every time there is a new push to the repo) - it's definitely not been easy to write all this and make it work, but it sure *does* work. So... you may get an idea of how this could work on Windows:

https://github.com/arturo-lang/arturo/blob/master/.github/workflows/windows.yml

P.S. Regarding the missing `gmp.h`, this is due to the fact that the "full" version requires the GMP (bignum) library to be installed. If I were you, I would first try building the MINI version (same as the normal one, minus a couple of not-so-commonly-used library, e.g. GMP): `./install mini`

**Comment by Kyllingene** [comment]
Ah, ok; thanks! I understand that building for Windows as a Linux user is much harder than the other way around (due to how proprietary Windows is); I very much appreciate this language as a great alternative to other interpreted languages, and even more so the amount of effort you put into it.

**Comment by drkameleon** [comment]
> I understand that building for Windows as a Linux user is much harder than the other way around (due to how proprietary Windows is)

I was using Windows up until 15-16 years ago. Then, I switched to Linux, where - as I developer - I loved the... freedom of movement. And then to Mac, where - the way I see it - you practically get all the good parts of Linux, minus the quirky ones. (Of course, I still use Linux on a daily basis, for server-related stuff). Funny thing is, after all these years, I can barely remember how to do even basic things on Windows... but I guess I'll have to lol. Finding a machine to install it on is pretty easy. :)

> I very much appreciate this language as a great alternative to other interpreted languages, and even more so the amount of effort you put into it.

And I thank you very much for your very kind words. I really appreciate it. I was bitten by the prog-lang design bug many many years ago, but it wasn't until Arturo that I decided to sit down and write something exactly the way (I though) it should be. It's still a work-in-progress of course, pretty much like every piece of software. But, I can assure you, I've already used the language - during my few-month break from open-source involvement - for 100% production code, and even to my surprise, it seems to be working fine :). So... that motivating in itself.

And of course, every little bit counts. In a few words: every contribution/suggestion/idea/question is more than welcome!

So... thanks again! 😉

**Comment by drkameleon** [comment]
> I "translated" the install script to nimscript (see attached file), but it still lacks some functionality (add arturo to path, check username, ...). The script uses nimscript's build tool functionality, so start it e.g. like "nim help install.nims" to see the possible tasks.
> 
> As I didn't find the matching "gmp.h", windows builds always get -d:nogmp flag. [install.zip](https://github.com/arturo-lang/arturo/files/8016893/install.zip)

Whoa! That's awesome! (and a great idea as well).

Before, we had some config.nims so that the language could be built using `nimble` - but given that this `config.nims` was being pulled by Nim and I ended up not knowing whether the active config was the one I was passing - via the command-line flags - or the one from `config.nims`, or a mix of both. And since, I don't want the language to depend too much on 3rd party tools (like nimble), I decided to simply remove it.

But your idea of having the installation script itself in NimScript definitely makes a lot of sense (since, if there is *one* thing that everybody should have before building Arturo *is* Nim itself). So, well done! :)

If you can/want, just make a pull request with the added file and I'm absolutely open to merge it (and if there are issues, we'll fix them along the road :wink)

**Comment by skydive241** [comment]
> If you can/want, just make a pull request with the added file and I'm absolutely open to merge it (and if there are issues, we'll fix them along the road 😉 ), so that you take all the credit you deserve. If not, I could add it myself.

😂😂😂 I'm really not interested in taking credits.... please add the script if you want or shredder it if you don't. 😊

**Comment by skydive241** [comment]
As a window user, I usually "oversee" files without extension.... so I also didn't see "package"....

I created a new task "package" ("nim package install.nims nameOfArturoAppWOextension").
[install2.zip](https://github.com/arturo-lang/arturo/files/8017975/install2.zip)

**Comment by drkameleon** [comment]
Thanks a lot - one more time! I'll have a thorough look into it and adapt it a bit to the general coding style of Arturo's codebase.

In any case, it looks very very interesting. As I said, you gave me one more reason to solve the 3-script installation mess from just one script. So, that's great! 😉
