### ISSUE TITLE
Attribute and AttributeLabel questions

### ISSUE THREAD

**Issue by celtic-coder** [arturo-lang/arturo#389]
Hi Yanis(@drkameleon),

I have some quick questions on attributes and attribute labels.

Most of the time in the documentation, the attribute follows the function with a "dot" in between and no space. However, in "[language.art](https://github.com/arturo-lang/arturo/blob/f01558ea5ed231a121c9577ea2439cbe7e368d08/docs/website/pages/documentation/language.art#L524-L526)", the attribute label is separated by a space from the function:

![space-before-dot](https://user-images.githubusercontent.com/11787866/145644815-25c32b7c-da04-4407-b35d-b9402e2b165c.png)

It seems the attribute (and the attribute label) can be separate from the function by space and that this is valid syntax - even though it is not the common occurrence in the documentation. I tried different examples in the playground as shown here:

![playground-examples](https://user-images.githubusercontent.com/11787866/145645688-4fd0fdef-d876-4d55-9d3c-fbd14b832825.png)

Is there a recommended notation or is it completely up to the user as to what they are most comfortable?

Also, in the examples above, where I was doing some testing, there is an invalid attribute label:

![split-abcde](https://user-images.githubusercontent.com/11787866/145646793-5944b41e-9890-492f-a3f6-778523d053e3.png)

This invalid attribute label is *silently ignored*. **Is this intentional?** Or should there be, at least, a warning raised?

Is the code doing something like the [attributeLabel?](https://arturo-lang.io/documentation/library/reflection/attributelabel-/) predicate in the [Reflection](https://arturo-lang.io/documentation/library/reflection/) portion of the documentation, by checking for an attributeLabel, but not necessarily checking if it is valid for the particular function?

Kind Regards,
Liam

**Comment by drkameleon** [comment]
Liam, Hi!

Very (very) good points!

Let me go through them one by one...

First of all, an attribute is defined as a dot (`.`) followed by letters/digits (and optionally the `?` character). If I had to define it as a regular expression, the complete form would be:

```regex
\.[a-zA-Z][a-zA-Z0-9\?]+
```

If that attribute has a trailing colon (`:`), then it's an Attribute Label.

- **Attributes** are like on/off switches.
- **Attribute Labels** are like optional parameters.

That being said, a plain attribute is 100% equivalent to an attributeLabel with the value: true. So... `.something` is exactly the same as writing `.something:true`.

----

> It seems the attribute (and the attribute label) can be separate from the function by space and that this is valid syntax - even though it is not the common occurrence in the documentation.

Regarding spacing, there is no rule at all - it simply doesn't matter. (personally, yes, I mostly prefer linking it with the preceding id, if it's a function name - because it looks more self-explanatory - but it's not a rule)

Have a look at this:

<img width="346" alt="Screenshot 2021-12-11 at 07 31 00" src="https://user-images.githubusercontent.com/1265028/145666892-c2bce569-2870-477a-84ab-c6074fa0ecec.png">

When the parser encounters the dot, it will finalize whatever token it was parsing, and start parsing an *attribute*.

The only "rule" here is (until I find a way to solve it - if that is even possible, given the very nature of the language):

if you pass an attribute to function, it must absolutely precede at least its last argument.

**Example:**

This is correct:

```
somefunction .someattr:123 somearg
```

This is NOT correct (or, to be more precise, it doesn't pass the attribute to the function, it simply pushes it onto the stack, because the evaluator has already found the number of arguments the function takes, so that was it):

```
somefunction somearg .someattr: 123
```

Of course, that means that a function without arguments cannot take attributes. But if you think about it, it makes total sense: if you have to have  something like `split.words` and `split` doesn't do anything on its own, then having something like `splitWords` would maybe be a better approach. (totally not by design, but I guess it's own of these productive... accidents that enforce good coding style lol)

----

> This invalid attribute label is silently ignored. Is this intentional? Or should there be, at least, a warning raised?

That's totally on purpose.

Attributes (or AttributeLabels for that matter) are just another value type of Arturo. And, yes, they can provide additional (optional) context for a specific function, but they are not hardcoded.

When define a new function, e.g. `function [x][ 2 + x ]`, you do enforce arity (how many arguments the function takes) - that's the only thing that the evaluator cares about. But there is no way to enforce specific attributes, even for system functions.

**What happens is:**

- Pass anything you want as an attribute - let's see it as a totally optional value, pushed onto a stack of "optional values"
- That value will remain there until a function "consumes" it.
- If one function call doesn't care about a specific attribute, that will be "passed on" to the next.

**The only 2 commands you'll (most likely) ever need:**

Obviously, you can totally control attributes from a user function. Let's see...

- Using [attr?](https://arturo-lang.io/documentation/library/reflection/attr-/), we may check if a given attribute is on the stack - but NOT consume it.

```red
f: function [x][
    print ~"x = |x|"
    
    print attr? 'a
    print attr? 'b

    print "checking them again"

    print attr? 'a
    print attr? 'b
]

f.a 2
```

[LIVE SNIPPET](https://arturo-lang.io/playground/?Pqmryu)

<img width="353" alt="Screenshot 2021-12-11 at 07 50 12" src="https://user-images.githubusercontent.com/1265028/145667401-a403872f-531a-4823-975d-c32c5ff35919.png">

- Using [attr](https://arturo-lang.io/documentation/library/reflection/attr/), we pop a given attribute from the stack. If the attribute isn't there, it will return `null`.

```red
f: function [x][
    print ~"x = |x|"

    print attr 'a
    print attr 'b

    print "checking them again"

    print attr 'a
    print attr 'b
]

f.a 2
```

[LIVE SNIPPET](https://arturo-lang.io/playground/?TewZvo)

<img width="361" alt="Screenshot 2021-12-11 at 07 52 43" src="https://user-images.githubusercontent.com/1265028/145667475-faebdf8c-abdb-4b4a-856b-b2a60221c24b.png">

---

**OK, now let's see a more reasonable example:**

```red
sayHello: function [person][
    if? attr? 'withColor [
        print color attr 'withColor ~"Hello |person|!"
    ]   
    else [
        print ~"Hello |person|!"
    ]
]

sayHello "John"
sayHello.withColor: #green "Jane"
```

[LIVE SNIPPET](https://arturo-lang.io/playground/?0n38rv)

**And the result :)**

<img width="387" alt="Screenshot 2021-12-11 at 07 55 52" src="https://user-images.githubusercontent.com/1265028/145667575-f0eff6d2-aa44-4ad4-8109-9b7c87a62ed5.png">

---

I hope I didn't manage to confuse you. If I did (or didn't), feel free to ask whatever comes to your mind. 😉

**Comment by celtic-coder** [comment]
Hi Yanis (@drkameleon),

Thank you very much for that comprehensive answer! 👍 That was certainly much more than what I expected, and you have provided much food for thought!

Don't worry about causing any confusion -- I enjoy working through such a well-thought-out explanation. It will take a while to wrap my head around the closing portion, but I will let you know if help is required.

The one thing that I appreciate in your explanation is your use of the Playground. This is an invaluable resource in getting to understand the language. 

I am a huge fan of proper syntax highlighting and the playground does this well. I am using the built-in REBOL highlighter in NotePad++ but it is insufficient, and I would like to update this to handle the range of Arturo keywords. (Something else to add to the To-Do list! 😄).

Thanks again for the time and effort you put into this explanation!

Kind Regards,
Liam

**Comment by drkameleon** [comment]
@celtic-coder 

Good morning!

Since I'm a total fan of proper syntax highlighting too, I would be more than willing to (help) create a syntax highlighter for NotePad++.

Currently, the "standard" highlighter (and the one I'm personally using and updating on a regular basis) is [the one for VSCode](https://github.com/arturo-lang/art-vscode-package) (runs on Mac and Windows and everything).

Here you can have a look at all the different syntax rules for highlighting, it's pretty straight-forward I think and it could easily serve as the basis for creating another highlighter: https://github.com/arturo-lang/art-vscode-package/blob/main/syntaxes/art.tmLanguage.json

Btw, Mike Parr has been working on something related (but more in the form of a standalone IDE/pretty-printer, for Windows): http://www.mikeparr.info/artlang.html

**Comment by drkameleon** [comment]
@celtic-coder Good morning!

Since we were talking about it, I decided to go on and start a Notepad++ highlighter.

I've based it off an existing highlighter I found for Rebol. I'm not sure if it's working (I've been struggling for hours only to get Notepad++ installed on macOS, but to no avail) - but I wouldn't totally... discard it lol.

Feel free to try it out if you want and/or contribute anything you might wish. 😃 

Here's the new repo in case you want to check it out:
https://github.com/arturo-lang/art-notepad-plus
