### ISSUE TITLE
Tab inserts tab, doesn't autocomplete

### ISSUE THREAD

**Issue by asampal** [arturo-lang/arturo#399]
In latest build the tab key simply inserts a tab rather than completing.

```
# v/0.9.78 b/194 @ 2022-01-13T20:38:47-05:00
# arch: amd64/windows
```

**Comment by drkameleon** [comment]
Thanks a lot for letting me know! 😉 

I've hadn't tested this too much (on Windows I mean), but we'll definitely have to figure out how to make it work. 

Which terminal are you using? (I'm asking because, from what I've seen, the more Unix-compliant the terminal, the more consistently Arturo's REPL works apparently...)

**Comment by asampal** [comment]
I'm using the new Windows Terminal, which, if you're taking about escape sequence and color and font support, should be really good.

**Comment by drkameleon** [comment]
> I'm using the new Windows Terminal, which, if you're taking about escape sequence and color and font support, should be really good.

Hmm... I'll have a look into it.

Arturo, for REPL-related, advanced command-line editing capabilities, relies on [LineNoise](https://github.com/antirez/linenoise). Generally, it's thought to be one of the most lightweight solutions that tend to work anywhere.

Here's the relevant part of Arturo's implementation:
https://github.com/arturo-lang/arturo/blob/master/src/helpers/repl.nim

An idea would be to try different key triggers (e.g. an alternative for <key>TAB</key>). I'll have to look into it to see if there's anything related reported and what the solution might be... 😉

**Comment by drkameleon** [comment]
Hmm... I realized what the issue is about as soon as I posted the answer above lol.

I guess the key is this `when not defined(Windows)` part - I honestly didn't even remember I had put that there... but it must have been because I couldn't get the library to work with windows at all.

Let's see...

**Comment by asampal** [comment]
If you want to create a build without that check I can try it on the new Windows Terminal and let you know if it works.

**Comment by drkameleon** [comment]
> If you want to create a build without that check I can try it on the new Windows Terminal and let you know if it works.

Hmm... My guess is it won't even compile. I had a look through the different builds and that's pretty much my conclusion. Give me some time to check it out and I'll let you know by tomorrow. (I've been working all day - mostly on Grafito - and I guess it's time to call it a day... 😄 )

There must be a way to make this work on Windows too.

**Comment by asampal** [comment]
Maybe take a look at Red's tab completion and, for Windows at least, it might be possible to implement something similar.

**Comment by drkameleon** [comment]
> Maybe take a look at Red's tab completion and, for Windows at least, it might be possible to implement something similar.

I've created a new branch/PR to experiment a bit with the Windows-version of the REPL.

If it builds successfully on Windows, I'll let you know and send you a binary so that you can play with it. 😄

**Comment by asampal** [comment]
Any luck with the new branch?

**Comment by drkameleon** [comment]
@asampal To be honest, apart from some initial research I did on the issue, I've pretty much put it aside (basically, working non-stop on Grafito and a mega-PR: https://github.com/arturo-lang/grafito/pull/8), but I'll get back to it. 😉

**Comment by drkameleon** [comment]
Looks like I've managed to fix it! :)

Here's what Arturo's REPL looks like on Windows (using Windows Terminal):
![linenoise](https://user-images.githubusercontent.com/1265028/156788963-5bf0dbe7-6bff-4a9e-a4cd-25e531b129e5.gif)

I'm double-triple-checking the PR and I'll merge.

Feel free to let me know what you can think (you can get latest nightly tonight; that is: in a few hours) 😉

**Comment by asampal** [comment]
Nice! Thanks for not forgetting about this, @drkameleon.

**Comment by drkameleon** [comment]
> Nice! Thanks for not forgetting about this, @drkameleon.

Not at all! It's just that I'm trying to do one million different things at the same time - so I have to prioritize! 😄 

Basically, I'm now working on a very, very interesting PR (https://github.com/arturo-lang/arturo/pull/413) that will probably bring Arturo to the next level.

And since most of the challenges I've faced so far are Windows-related, I convinced... myself to set up a Windows machine and start trying things out first-hand. 

Well, that being said, I ended up solving (hopefully) this one as well. 😉

**Comment by asampal** [comment]
Looks good! 

WRT attributes of `logical` type, I see that currently the completion appends a colon `:`. Since supplying a `true` value for these is unnecessary, would it be possible to not add the colon character (implying that something must be supplied)?

**Comment by drkameleon** [comment]
> Looks good!

😄 

> WRT attributes of `logical` type, I see that currently the completion appends a colon `:`. Since supplying a `true` value for these is unnecessary, would it be possible to not add the colon character (implying that something must be supplied)?

I think I know what you mean.

First, let me explain how attributes work in Arturo.

An attribute without a value, that is an `:attribute`, is like a switch - where you turn some option "on".

Let's see the function [`split`](https://arturo-lang.io/documentation/library/collections/split/):

<img width="706" alt="Screenshot 2022-03-05 at 15 02 33" src="https://user-images.githubusercontent.com/1265028/156886668-d9d46cba-f6ef-4c12-8dcd-ee07680054fc.png">

On the other hand, we have `:attributeLabel`s, that is *attributes* with some given value.

E.g.

<img width="355" alt="Screenshot 2022-03-05 at 15 05 23" src="https://user-images.githubusercontent.com/1265028/156886750-715c1608-8fe6-4271-bf1c-023a36cf9560.png">

As you have said your self, the first case (plain `:attribute`s) are actually equivalent to an `:attributeLabel` with a *true* value). In a few words:

This:

```red
split.words "one two three"
```

Is 100% equivalent to:

```red
split.words:true "one two three"
```

-----

All that being said (quite an unnecessarily ultra-long explanation, but ok lol), you are perfectly right. Basically, the issue is solely related to the REPL. The problem(?) is that it considers logical attributes like every other attribute (which is meant to take a value, hence the colon), while logical attributes are merely used like switches.

So... added to my TODO list! 🚀

**Comment by asampal** [comment]
I should have mentioned that I wasn't confused about attributes in general, to save you some typing :0
