### ISSUE TITLE
Json cannot be parsed if keys contain e.g. "_"

### ISSUE THREAD

**Issue by skydive241** [arturo-lang/arturo#426]
Json data cannot be parsed if keys contain symbols other than letters and "?",

```
data: read.json "https://api.github.com/repos/arturo-lang/nightly/releases/latest"
print data\assets\8\browser_download_url
```
results in

```
>> Runtime | File: test.art
     error | Line: 49
           |
           | dictionary key not found: browser
           | perhaps you meant... uploader ?
           |                or... url ?
           |                or... name ?
```

Arturo built with (parse.nim)
```
    PermittedIdentifiers_In     = PermittedColorChars + {'_', '?'}
```

leads to the correct output
```
https://github.com/arturo-lang/nightly/releases/download/tag-2022-02-08/arturo-0.9.78-2022-02-08-Windows-full.zip
```

**Desktop:**
 - OS: Windows 10

**Comment by drkameleon** [comment]
Given that identifiers in Arturo consist only of letters and digits (`[a-zA-Z0-9]+\??`) and that's valid for `:path` values as well (e.g. a/b/c/3/d), I would suggest something like:

```red
print data\assets\8\["browser_download_url"]
```

or

```red
print get data\assets\8 "browser_download_url"
```

**Comment by skydive241** [comment]
Ah, okay, that's it! I tried to parse json in the way you did in update.art, e.g. 

```download .as:"art.tar.gz"  (data\assets \ asset) \ "browser_download_url"```, 

but that isn't the correct way. So I tried using underscores....

But e.g.

```download .as:"art.tar.gz"  data\assets\[asset]\["browser_download_url"]```

is correct. Thank you!

**Comment by drkameleon** [comment]
Good morning! 

Glad we got it to work! 😉 

The thing is `:path`s (a\b\c\d) and `:pathLabel`s have undergone some changes, so what you found above is something that is basically a leftover that does not want anymore.

Right now (and the way things will most likely remain), here is how it works:

- `a\b\2\c` means the field "c" of the 2nd element of the field "b" of a
- which would be the equivalent of: `a\["b"]\[2]\["c"]`
- the exact same thing would work for `:pathLabel`s as well (for writing instead of access), e.g.: `a\b\2\c: "hello"`
- in a few words, if you have constant-literal fields/indices, you just write them as they are. if they are variables, or an expression that is to be calculated (yes, that works too!), just put them in a block (`[`...`]`)

And here's everything in a nutshell (because I always prefer code examples to long explanations lol):

<img width="633" alt="Screenshot 2022-02-09 at 09 27 22" src="https://user-images.githubusercontent.com/1265028/153155706-f6985593-fa8a-4a08-891a-a20994eac958.png">
