### ISSUE TITLE
"symbol not found: clear" in latest Windows nightly

### ISSUE THREAD

**Issue by asampal** [arturo-lang/arturo#437]
**Describe the bug**
In the tag-2022-02-11 Windows full build I get the following when starting Arturo:

```
>> Runtime | symbol not found: clear
     error | perhaps you meant... blend ?
           |                or... alias ?
           |                or... break ?

[process exited with code 1 (0x00000001)]
```

Windows 11 Pro

**Comment by drkameleon** [comment]
Ooops... I'm fixing it right now.

Given that terminal support for Windows is not as complete as it should be, yesterday I decided to cleanup the code for the `clear` command (basically, so that it works for Web/JS builds), but I also "removed" it for Windows (since it wasn't doing anything anyway): https://github.com/arturo-lang/arturo/blob/master/src/library/Io.nim#L52. But it's absolutely used by the `console` script (the one that initiates Arturo's REPL): https://github.com/arturo-lang/arturo/blob/master/src/scripts/console.art#L65

So,apparently, there was a reason for the way things before the change: the `clear` command should exist no matter what, even if it does nothing (and for WIndows as well - until the Windows-specific Terminal-related functionality is fixed).

So, I'm reverting it right now. Thanks for letting me know! 😉
