### ISSUE TITLE
Could CI builds include all components?

### ISSUE THREAD

**Issue by asampal** [arturo-lang/arturo#449]
It would be nice if all the CI automated builds (not just the nightly) included all components needed to run Arturo, not just the main executable.

**Comment by drkameleon** [comment]
Can you please elaborate a bit?

Are you referring to the missing DLLs for Windows?

Right now, at least for the current CI setup, all builds (except for the JS/WEB builds) come with the unit-testing utility, that means for every run there are over 370 tests that have to be successfully completed before a build "passes". So, obviously, at least for the current setup (even if that is MSYS2), the binary does work.

But I've totally noticed that e.g. on Windows different things may be needed as well (and I'll have to decide which of them to static-link or just plainly bundle with the binary) - which is quite bad, but not-to-bad given the provided extra functionalities.

**Comment by asampal** [comment]
Yes, I meant the DLLs. I tried to copy the most recently CI-built arturo.exe over the full Windows nightly fileset and got an error about what I think was a missing DLL.

**Comment by drkameleon** [comment]
Hmm... I see what you mean.

I'll look into it and make sure all the DLLs are there in the uploaded "artifact". Basically, making sure which DLLs are needed and which are not is the very next thing I'm going to do. So... let's see... 😄

**Comment by asampal** [comment]
Just pulled down the latest auto-build and it looks good. 

One minor point - the produced zip contains another with the same name, so one level should be removed.

**Comment by drkameleon** [comment]
I think I'm quite close (at least for the main branch).

Can you please have a look into the latest build, e.g.: https://github.com/arturo-lang/arturo/actions/runs/1946398550

It should be correct.

---

P.S. Now, the next challenge is to figure out what the missing DLLs are for the upcoming PR (which - especially for Windows - introduces quite a few dependencies...) Let's see...

**Comment by asampal** [comment]
Just noticed that some of the newer CI builds are back to not including the DLLs. The one below followed builds that did include them, so not clear what's going on. 

e.g. https://github.com/arturo-lang/arturo/actions/runs/1951277677

**Comment by drkameleon** [comment]
I know, you're absolutely right.

Basically, I fixed the DLL issue for the main branch. Given that the run you're referring to is for the upcoming PR, I have left it as it was and the reason is quite simple: before I include the needed DLLs, I have to figure out which ones we are talking about. And given that this new PR introduces more than a handful of new things, I've spent practically all morning compiling and recompiling... Now, as we speak actually, I'm seeing which of the dependencies can be statically-linked and which cannot (e.g. WebView2Loader.dll). When this... marathon is over, I'll update the PR workflows so that the correct DLLs are included.

P.S. This long-awaited PR is slowly getting closer to merging. 😄
