### ISSUE TITLE
Add ability to search across functions by descriptive string or types

### ISSUE THREAD

**Issue by asampal** [arturo-lang/arturo#458]
An apropos command would be a nice addition to the REPL. For getting the lay of the land, Arturo currently has `help` and `info`. The first is all-inclusive, showing all available functions, while the latter focuses on one, specifically. Sometimes you don't know exactly what you're looking for, but you know how the desired function might have been described.

As an enhancement, an apropos-type of lookup would take a string (or maybe regex) and search across all functions, returning those where there is a match in the description (perhaps example comments too?).

Potentially, a variant of apropos could take a set of types and return results based on parameters matching.

Here's Julia's "apropos" as an example:

![image](https://user-images.githubusercontent.com/281639/157276915-cf8f4360-92a5-42cf-9419-ad23d6138d47.png)

**Comment by drkameleon** [comment]
Another super-interesting idea!

> Potentially, a variant of apropos could take a set of types and return results based on parameters matching.

I had thought of that part specifically, but your proposal is even more complete.

Noted! 😉

**Comment by drkameleon** [comment]
So, I'm doing some pre-release cleanup (https://github.com/arturo-lang/arturo/pull/461) and I decided to make the REPL a tiny bit better as well... 😄 

Part of this transition was to actually remove the `help` command and convert it into a REPL-only function; and thus [written 100% in Arturo](https://github.com/arturo-lang/arturo/blob/general-cleanup/src/scripts/console.art#L109-L117).

The exact same thing happened with your suggestion, which became [a new REPL-only function](https://github.com/arturo-lang/arturo/blob/general-cleanup/src/scripts/console.art#L119-L175) (`lookup`); with which we can now look up any built-in function either **(a)** given a string (where you we try to find it in the function name, function description, attribute name, or any of the attribute descriptions), or **(b)** given a type (where you try to find function with one of the parameters coinciding, or - with the option `.returns` - in its returned arguments).

Here's what the whole thing currently looks like:

### Our new `help` function

<img width="1023" alt="Screenshot 2022-03-10 at 12 41 52" src="https://user-images.githubusercontent.com/1265028/157655866-6d95a050-f4d4-4f1f-959a-499445cd72c1.png">

### The brand-new `lookup` function, in action

<img width="721" alt="Screenshot 2022-03-10 at 12 42 12" src="https://user-images.githubusercontent.com/1265028/157655933-7f8b3ae7-a357-4128-a5b3-9b76520f7d57.png">

#### Looking up by some string

<img width="1084" alt="Screenshot 2022-03-10 at 12 42 53" src="https://user-images.githubusercontent.com/1265028/157656002-59c924fc-4729-4552-88cc-2f669e647ff4.png">

#### Looking up using some type

<img width="995" alt="Screenshot 2022-03-10 at 12 43 16" src="https://user-images.githubusercontent.com/1265028/157656072-ee6f18ca-6a62-4f4c-880b-6e4eab8636ee.png">

and...

<img width="1067" alt="Screenshot 2022-03-10 at 12 43 31" src="https://user-images.githubusercontent.com/1265028/157656106-6bafa4d7-228a-44ca-8f38-0ac45d81c736.png">

Let me know what you think! 😉

**Comment by celtic-coder** [comment]
Excellent work, Yanis! 👍

**Comment by drkameleon** [comment]
@celtic-coder Liam, thanks a lot! 😄  I'm doing my best!

**Comment by asampal** [comment]
Yup, this is pretty much it, @drkameleon! 

The only thing I would say is that the description should maybe be chaged from:
```
lookup built-in function by given string or type
```

to

```
lookup functions by given descriptive string or signature types
```

I assume that this would also work against user-defined functions, no?

**Comment by drkameleon** [comment]
> I assume that this would also work against user-defined functions, no?

Well, the truth is... it didn't; until now 😄 

Initially, built-in & user functions were - internally - something fundamentally different. Hence, my idea of focusing on built-in function, since the two types didn't share much in common (that could be e.g. searchable)

Given the changes in the past few months, functions' structure right now is more-or-less quite uniform... so, why not?!

Lookups will now be working on everything + I also changed the description accordingly, I agree it would suit its functionality better. 😉

**Comment by asampal** [comment]
Great! Just checked it out. I think this can be closed.

**Comment by asampal** [comment]
I just noticed that string lookups return results where the search term is just a substring. While this is useful, being able to specify whole word, prefix, or a more complex search pattern, e.g. with a regex,  would be good. This is why I asked about regexes as a distinct type that could be used here and elsewhere.

**Comment by drkameleon** [comment]
Interesting that you mention it.

First of all, let me tell you that I'm a huge fan of regular expressions (as a matter of fact, I think I tend to over-use them, but ok... lol).

That being said, as you must have already noticed, Arturo already supports RegEx's quite extensively (e.g. [`replace`](https://arturo-lang.io/documentation/library/strings/replace/)), although as a rule using the option `.regex` (since, well, a regex is actually a string after all).

But I totally get your point and I admit I had thought of it being a distinct type. Given the REBOL-ish nature of Arturo, type-wise, I guess this could make things smoother in many case (plus, avoid a) the constant use of `.regex`, b) not being sure what to escape within a regex ... string).

Let me think about it...

I'll open a separate issue for that and once solved, I guess all functions that work with a `.regex` option could be converted. 😉

**Comment by drkameleon** [comment]
Regex-based lookups are in :)

<img width="1053" alt="Screenshot 2022-03-12 at 13 23 28" src="https://user-images.githubusercontent.com/1265028/158017810-8af8e1e2-8e47-4d0c-ac97-9f765a0e0bbb.png">

P.S. It works exactly the same way it does for strings, only we use a `:regex` value (`{/.../}`) 😉

**Comment by asampal** [comment]
What is the difference between lookup by :string vs :literal? Are they basically equivalent? From the tests I did, it seems so.

Maybe it would make sense for `lookup 'foo` to be a shorter form of `lookup {/\Wfoo\W/}`, or whole word match.

**Comment by drkameleon** [comment]
basically, in that particular case (the `lookup` function) there is no difference, so what you suggest could be an interesting approach. I'll elaborate a bit more on discord regarding literals and the way they work in Arturo. 😉

**Comment by drkameleon** [comment]
Considering this solved... :)

P.S. In case there is anything missing, we can of course re-open it again in the future.
