### ISSUE TITLE
How to compile without GTK?

### ISSUE THREAD

**Issue by xigoi** [arturo-lang/arturo#65]
The documentation says that GTK is required only for “complete” builds, but it doesn't specify how non make a non-“complete” build. Any help?

**Comment by drkameleon** [comment]
@xigoi You're correct. Well, you caught me in the middle of huge makeover (the documentation included), so I would have added that too... 

Basically, if you want to build Arturo, it's:

```bash
./install```

For "mini" builds (less dependencies, a tiny bit less library function), it's:

```bash
./install mini```

(and it will get installed into `~/.arturo/bin` - so it would be advisable to make sure this path is in your $PATH variable, and set in your `~/.profile`, or `~/.bashrc`, or `~/.zshrc` too )

Please, let me know how it went! :)

**Comment by xigoi** [comment]
Thank you, it went well! I just had to write `bash install mini` instead of `./install mini` because the file doesn't have a shebang and I'm using Fish.

**Comment by drkameleon** [comment]
Great to hear it worked!

Regarding the missing shebang line, I totally get what you mean.

Basically, I had something like `#!/usr/bin/env bash`, then changed it to `#!/usr/bin/env sh` and then decided to completely remove it since - I thought - it was working both for `zsh` and `bash`, where I had tested it.

Now, you're making me re-consider after all. Perhaps, a `#!/usr/bin/env sh` would have been more universal... Any ideas? (Btw, which OS are you running it on?)

All ears for feedback/suggestions/questions - just ask me here, or open a new issue! :)

**Comment by xigoi** [comment]
I think `#!/usr/bin/env sh` should be good :)

I had already installed the complete build on my laptop with Manjaro Linux and then I wanted to also get it into Termux on my Android phone, which obviously can't have support for a GUI library.

**Comment by drkameleon** [comment]
> I think `#!/usr/bin/env sh` should be good :)

I'm now experimenting (again) a bit with `/usr/bin/env bash`, this is the only one that seems to be working flawlessly for Mac, Linux and the CI builds. I'm working on it right now on a separate branch and will merge on the CI build completes.

> I had already installed the complete build on my laptop with Manjaro Linux and then I wanted to also get it into Termux on my Android phone, which obviously can't have support for a GUI library.

So... you've installed Arturo on your phone?! That's something!
Totally looking forward to hear what you think! :)

**Comment by xigoi** [comment]
![Screenshot_2021-02-01-09-46-38-496_com termux](https://user-images.githubusercontent.com/16985175/106441426-53d22200-647a-11eb-8e64-8274c1b1124a.jpg)

Here is a screenshot. I've noticed that some features mentioned in the doc don't work, such as pipes `"hi" | print"` and ranges `0..9`. Is that okay?

**Comment by drkameleon** [comment]
That looks totally awesome! Thanks! :)

Regarding pipes, it's still an experimental feature, but I believe it will finally make into the master branch (it was in, but since I'm cleaning up a couple of things, I guess it had to wait...)

Regarding ranges... The range command does work (`range 0 9`). What apparently doesn't is the corresponding alias (`..`). So... I'm opening an issue for that and I'll do my best to fix it asap. :)

Keep the feedback coming! ;-)

**Comment by drkameleon** [comment]
And fixed! ;) 

<img width="251" alt="Screenshot 2021-02-01 at 11 10 14" src="https://user-images.githubusercontent.com/1265028/106444730-6f3f2c00-647e-11eb-8a4f-b0f35c3c6499.png">


(There must be several other symbol aliases that have not been re-assigned, so I'll have to quickly go through the code and see what's missing...)

**Comment by xigoi** [comment]
I started making a Vim plugin for Arturo, currently it has syntax highlighting. https://github.com/xigoi/vim-arturo

**Comment by drkameleon** [comment]
> I started making a Vim plugin for Arturo, currently it has syntax highlighting. https://github.com/xigoi/vim-arturo

Wow! Great! :)

I'll take it for a test drive as soon as I can!

Btw, for reference, you may also take a look into the plugin for VSCode (it's the most complete and up-to-date so far)
