### ISSUE TITLE
arturo-lang.io site is down

### ISSUE THREAD

**Issue by chenrui333** [arturo-lang/arturo#68]
👋  site is down.

![image](https://user-images.githubusercontent.com/1580956/106477861-9a258200-6476-11eb-92ea-9ef4dbb1839b.png)

---

relates to https://github.com/Homebrew/homebrew-core/pull/70145

**Comment by drkameleon** [comment]
Thanks a lot for the reminder!

Apparently, I brought it down in order to revamp it a bit and forgot about and focused on improving Arturo.

However, since I'm currently working non-stop on the project, chances are the website will be back up very very soon!

Stay tuned! :)

**Comment by chenrui333** [comment]
Nice, thanks for the update! 🎉

**Comment by chenrui333** [comment]
@drkameleon looks like the site is still down?

**Comment by drkameleon** [comment]
@chenrui333 You have a point. I guess I got carried away by the project itself and forgot about the website (perhaps using as an excuse that the main documentation is [at the Wiki](https://github.com/arturo-lang/arturo/wiki)).

In any case, I will do my best to get something up soon. :)

Looking forward to hear more feedback about the language/project! ;-)

**Comment by drkameleon** [comment]
@chenrui333 Since you mentioned it again, I finally decided to get back to work with the website. And, even though it's not 100% ready yet, I've definitely made a couple of steps forward and decided to set it up - with a brand new design/layout I've been preparing.

https://arturo-lang.io

Also, I've [opened a new discussion](https://github.com/arturo-lang/arturo/discussions/179), so... feel free to let me all know what you think about it! :)
